### PR TITLE
[164] Internationalise

### PR DESCRIPTION
**Pull request by j-maynard**
There's a falkey test in this PR and the internalisation libraray isn't the best.  Look for an alternative or write an alternative for beta or more eyes may help to configure things so that they are more stable.

### CODE REVIEW

**Comment by andyjpb** [comment]
Curiosity: Why is the test flaky? I can't see a source of non-determinism?

General comment: The API for this library seems very cumbersome. In terms of the source code for HTML pages, that'll make it a royal PITA to write content for. Is there something more like GNU gettext that has a better API and also uses more standard translation catalogue files that might be compatible with our translator's toolchain?

An API such as _("This is a translatable string") is quite common.

It has a few advantages:
 * _ is an innocuous character that doesn't add much noise to the appearance of the source and is bound to the translation function.
 * This function is passed a string in one language so that the content in the source code itself is readable.
 * Because strings appear directly in the source, it's easy to use grep (or other tools) to find out the context for every translated string. Sometimes (often?) this is important so that enough detail can be provided to the person doing the translation.
 * It's not necessary to make any extra declarations when writing content for pages: You just write the content as usual and add the special _("") sugar to anything that needs translating. You don't have to declare a structure containing the different parts of the message and then format it all back together from symbolic tokens later.
 * In some languages (not sure about TS) _ is a macro that replaces itself at compile time with a symbolic lookup so that it's equally fast in all languages and doesn't have to do a lot of string processing at runtime. This is probably a minor benefit in our case tho'.

**Comment by andyjpb** [comment]
> Is there something more like GNU gettext that has a better API and also uses more standard translation catalogue files that might be compatible with our translator's toolchain?

>     * Because strings appear directly in the source, it's easy to use grep (or other tools) to find out the context for every translated string. Sometimes (often?) this is important so that enough detail can be provided to the person doing the translation.

See https://en.wikipedia.org/wiki/Gettext for an overview of the translating workflow, including how we might give hints to translators about what's going on at the point the message appears.

**Comment by andyjpb** [comment]
Hello again!

We are probably best using an off the shelf library because Welsh has cardinal plural rules more like Slovenian than English: https://www.unicode.org/cldr/charts/44/supplemental/language_plural_rules.html#cy

i.e. it has more than the two forms of plural we have in English (1 library, 2 libraries; 1 banana, 2 bananas); it's more like the English ordinal rules where there's a special case for "a few" of something: (1st, 2nd, 3rd, 4th, *th...)

Apropos gettext, https://en.wikipedia.org/wiki/Gettext mentions that there's a version for Node.js. Could that be suitable for us?

**Comment by j-maynard** [comment]
So I did a bit of a spike yesterday around [this gettext ](https://github.com/guillaumepotier/gettext.js/) implementation for Node yesterday.  Although it is good it doesn't cover all of the things we would need it to do in a web application and to use it well we would need to write a lot of additional code to cover all the uses of language within an app.  Most of this is covered with i18next middleware package included in this PR.

**Comment by j-maynard** [comment]
The tests can be a bit flakey when the i18next middleware fails to load properly in the test...  This may either be an issue with how I've implemented the code or because it needs to be loaded as part of the test itself.

**Comment by easternbloc** [comment]
I'm going to say I'm happy to approve this for now. We need to add a tech debt ticket around the flakey tests but for the purposes of Alpha I think we should press ahead.

**Pull request merged**
